user  nginx;
worker_processes  auto;

events {
    worker_connections 1024;
}

http {
    sendfile on;

    upstream backend_upstream {
        server backend:3000;
    }

    upstream frontend_upstream {
        server frontend-web:3000;
    }

    server {
        listen 80;

        location /api/ {
            proxy_pass http://backend_upstream/;
        }

        location / {
            proxy_pass http://frontend_upstream/;
        }
    }
}
